name: Package Release

on:
  push:
    branches:
      - main

jobs:
  build-and-tag:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-dotnet@v1
      name: Setup .NET Core
      with:
        dotnet-version: '3.1.x' # SDK Version to use; x will use the latest version of the 3.1 channel

    - name: Publish Release
      run: dotnet publish -r linux-arm -c Release -o latestrelease *sln

    - run: mkdir -p release

    - name: Package files in tar
      run: tar -cf release/petfeeder.tar latestrelease/*

    - run: rm -rf latestrelease

    - run: git tag $(dotnet run --project Almostengr.PetFeeder.Api --version)
    - run: git push --tags
    - run: git push

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with: 
        files: fptrelease/petfeeder.tar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}